# Generated by Django 3.0.3 on 2020-02-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_delete_useradds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='likes',
            new_name='isLiked',
        ),
    ]
