# Generated by Django 3.0.3 on 2020-02-27 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0003_auto_20200226_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='postID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admin_page.Post'),
        ),
    ]
