# Generated by Django 3.0.3 on 2020-02-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0004_auto_20200227_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userAdds',
        ),
    ]
