# Generated by Django 3.0.3 on 2020-02-27 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200227_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstate',
            name='user',
        ),
        migrations.AddField(
            model_name='userstate',
            name='use_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
