# Generated by Django 3.0.3 on 2020-02-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200227_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstate',
            old_name='use_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='userstate',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
