# Generated by Django 3.0.3 on 2020-02-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200227_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstate',
            old_name='user_id',
            new_name='user',
        ),
    ]
