# Generated by Django 3.0.3 on 2020-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200227_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstate',
            name='is_blocked',
            field=models.BooleanField(null=True),
        ),
    ]
