# Generated by Django 3.0.3 on 2020-02-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200224_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='likes',
            field=models.BooleanField(default='null'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
