# Generated by Django 3.0.3 on 2020-02-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200224_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='likes',
            field=models.BooleanField(null=True),
        ),
    ]
