# Generated by Django 3.0.3 on 2020-02-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200227_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comId',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='reply',
        ),
    ]
