# Generated by Django 3.0.3 on 2020-02-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200227_0855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
