# Generated by Django 3.0.3 on 2020-02-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200225_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likes',
            field=models.NullBooleanField(),
        ),
    ]
